version: "3"
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - redis
    restart: always
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=production

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    depends_on:
      - redis
    restart: always
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=production

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8080:8080"
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always

  redis_replica:
    image: redis:alpine
    depends_on:
      - redis
    command: redis-server --replicaof redis 6379 --appendonly yes
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - client
    restart: always

volumes:
  redis_data: